spring.datasource.url=jdbc:postgresql://localhost:5432/devdb
spring.datasource.username=ups
spring.datasource.password=ups123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG

jwt.secret=mySecretKeyForJWT2024MustBeAtLeast256BitsLongForHS256Algorithm
jwt.expiration=1800000
jwt.refresh-expiration=604800000