server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/devdb}
spring.datasource.username=${DB_USERNAME:ups}
spring.datasource.password=${DB_PASSWORD:ups123}

spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}

logging.level.root=INFO
logging.level.ec.edu.ups.icc.fundamentos01=DEBUG
logging.level.org.hibernate.SQL=DEBUG

jwt.secret=${JWT_SECRET:mySecretKeyForJWT2024MustBeAtLeast256BitsLongForHS256Algorithm}
jwt.expiration=${JWT_EXPIRATION:1800000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}
